version: '3.8'

services:
  db:
    build: ./db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: employees
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: app
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/employees?allowPublicKeyRetrieval=true&useSSL=false
      DB_USER: root
      DB_PASSWORD: example
    ports:
      - "8080:8080"
